### ISSUE TITLE
SharpAI and AutoJungle Problems

### ISSUE THREAD

**Issue by Nitroxko** [berbb/PortAIO-v2#6]
# AutoJungle

Get's this error in console and no menu shows up for AutoJungle, something breaks on loading complete:
` Failed to notify OnLoadingComlete listener!
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "AutoJungle.Resource.en.resources" was correctly embedded or linked into assembly "PortAIO" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Resources.ResourceManager.GetString(String name)
   at AutoJungle.Program.CreateMenu()
   at AutoJungle.Program.OnGameLoad()
   at PortAIO.Init.LoadUtility()
   at PortAIO.Init.Initialize()
   at PortAIO.Init.Loading_OnLoadingComplete(EventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at EloBuddy.SDK.Events.Loading.CallLoadingComplete()`

# SharpAI
Menu does not load properly, actually loads a new menu, has bad turret logic.
![20 59 53 261](https://cloud.githubusercontent.com/assets/3257523/19616149/94fc6d6e-97d1-11e6-96fd-6c9d4a6a42f5.png)

**Comment by berbb** [comment]
Bad turret logic is probably in the original also since I haven't even touched the code since I ported it
which means it's probably gonna take longer to "fix".

**Comment by Nitroxko** [comment]
And what about AutoJungle?

**Comment by berbb** [comment]
if i haven't said anything about it or haven't closed the issue then it's probably fixable though, ARAMDetFull is still my first priority in AutoPlay.

**Comment by berbb** [comment]
Auto Jungle has been fixed. 

I'll take a look at SharpAI, but the menu issue isn't actually an issue, AutoJungle is an SDK assembly so it'll open a SDK menu. But also, SharpAI doesn't have a menu so that's why you didn't see anything in the SDK menu, I'll put a message in the chat letting you know SharpAI loaded to prevent confusion.
